
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Mon Jan 09 14:41:09 ART 2023
//----------------------------------------------------

package parserL;

/** CUP generated interface containing symbol constants. */
public interface symLang {
  /* terminals */
  public static final int LPARENT = 8;
  public static final int RPARENT = 9;
  public static final int PLUSPLUS = 3;
  public static final int FAULTY = 42;
  public static final int LBRACKET = 12;
  public static final int ASTERISK = 5;
  public static final int REWARDS = 34;
  public static final int SLASH = 6;
  public static final int DOUBLE = 38;
  public static final int INTEGER = 37;
  public static final int INT = 26;
  public static final int INIT = 28;
  public static final int MINUS = 4;
  public static final int SEMICOLON = 14;
  public static final int AND = 21;
  public static final int LT = 23;
  public static final int OR = 20;
  public static final int BOOL = 27;
  public static final int COMMA = 19;
  public static final int GEQ = 24;
  public static final int PLUS = 2;
  public static final int MAIN = 31;
  public static final int EXCLAMATION = 7;
  public static final int ID = 41;
  public static final int PROCESS = 29;
  public static final int EOF = 0;
  public static final int RBRACKET = 13;
  public static final int EQUAL = 17;
  public static final int TRUE = 39;
  public static final int error = 1;
  public static final int DOUBLE_EQUAL = 18;
  public static final int CONTROLLER = 35;
  public static final int GLOBAL = 32;
  public static final int COLON = 15;
  public static final int LBRACE = 10;
  public static final int ENUM = 33;
  public static final int RBRACE = 11;
  public static final int LEQ = 25;
  public static final int RIGHTARROW = 16;
  public static final int FALSE = 40;
  public static final int RUN = 30;
  public static final int GT = 22;
  public static final int INTERNAL = 43;
  public static final int GOAL = 36;
}

